name: system CI

on:
  pull_request:
    branches: [main]
  
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        compiler: [ g++-12 ]
        include:
          - os: ubuntu-latest
            compiler: g++-12
            target: Linux

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: mkdir build
        run: |
          mkdir build
          cd build
          cmake ..
          make

      - name: run
        run: ../../../../bin/system/repeated_execution_example