name: system CI

on:
  pull_request:
    branches: [main]
  
  workflow_dispatch:

defaults:
  run:
    shell: bash

inputs:
  source-dir: 
    default: ${{ github.workspace }}
  build-dir:
    default: "${{ github.workspace }}/../build"
    requried: true
  build-type:
    default: 'Release'
    required: true

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        compiler: [ g++-12 ]
        include:
          - os: ubuntu-latest
            compiler: g++-12
            target: Linux

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: run
        ./bin/system/repeated_execution_example