name: system CI

on:
  pull_request:
    branches:
      - main

inputs:
  source-dir: 
    default: ${{ github.workspace }}
  build-dir:
    default: "${{ github.workspace }}/../build"
    requried: true
  build-type:
    default: 'Release'
    required: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
    - uses: actions/checkout@v1

    - name: cmake ..
      run: |
        cmake ..
        make
        ./bin/system/repeated_execution_example
